# Generated by Django 6.0.6 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20, unique=True, verbose_name='ID записи')),
                ('exercise_id', models.CharField(db_index=True, max_length=20)),
                ('activity_id', models.CharField(max_length=20)),
                ('question_id', models.CharField(blank=True, default='', max_length=20)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('course_id', models.CharField(db_index=True, max_length=20)),
                ('task_id', models.CharField(blank=True, default='', max_length=20)),
                ('module_id', models.CharField(blank=True, default='', max_length=20)),
                ('student_id', models.CharField(blank=True, default='', max_length=20)),
                ('user_course_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('checking_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, default='')),
                ('files', models.JSONField(blank=True, default=list)),
                ('check_comment', models.TextField(blank=True, default='')),
                ('exercise_title', models.CharField(max_length=500)),
                ('exercise_description', models.TextField(blank=True, default='')),
                ('exercise_instruction', models.TextField(blank=True, default='')),
                ('exercise_attempts', models.CharField(blank=True, default='', max_length=10)),
                ('exercise_min_result', models.CharField(blank=True, default='', max_length=10)),
                ('task_title', models.CharField(max_length=500)),
                ('task_index', models.CharField(blank=True, default='', max_length=50)),
                ('module_title', models.CharField(blank=True, default='', max_length=500)),
                ('course_title', models.CharField(blank=True, default='', max_length=500)),
                ('user_name', models.CharField(max_length=300)),
                ('user_bio', models.TextField(blank=True, default='')),
                ('user_email', models.EmailField(blank=True, default='', max_length=300)),
                ('user_region_code', models.CharField(blank=True, default='', max_length=200)),
                ('user_timezone', models.CharField(blank=True, default='', max_length=10)),
                ('user_progress', models.CharField(blank=True, default='', max_length=10)),
                ('user_birthday', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=300)),
                ('checked', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('skip', models.BooleanField(default=False)),
                ('checking', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('invisible', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('result_score', models.CharField(blank=True, default='', max_length=10)),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('stars', models.CharField(blank=True, default='0', max_length=5)),
                ('min_score', models.CharField(blank=True, default='', max_length=5)),
                ('format', models.CharField(blank=True, default='', max_length=5)),
                ('flow_num', models.CharField(blank=True, default='', max_length=10)),
                ('chat_id', models.CharField(blank=True, default='', max_length=50)),
                ('manual_check', models.BooleanField(default=False)),
                ('check_minutes', models.CharField(blank=True, default='', max_length=10)),
                ('raw_data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise record',
                'verbose_name_plural': 'Exercise records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exercise_id', 'user_id'], name='parser_exer_exercis_5403ba_idx'), models.Index(fields=['user_name'], name='parser_exer_user_na_e3b1d3_idx')],
            },
        ),
    ]
